# Generated by Django 4.0.2 on 2022-02-23 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('userid', models.IntegerField(blank=True, verbose_name='User id')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=30, unique=True, verbose_name='Account Name')),
                ('account_number', models.IntegerField(blank=True, verbose_name='Account Number')),
                ('account_description', models.CharField(blank=True, max_length=300, verbose_name='Account Description')),
                ('account_category', models.CharField(choices=[('A', 'Assets'), ('L', 'Liabilities'), ('EQ', 'Equity Accounts'), ('R', 'Revenues'), ('EX', 'Expenses'), ('O', 'Other')], max_length=30, verbose_name='Account Category')),
                ('account_subcategory', models.CharField(blank=True, max_length=30, verbose_name='Account Subcategory')),
                ('normal_side', models.CharField(blank=True, max_length=5, verbose_name='Normal Side')),
                ('Date_time_added', models.DateTimeField(auto_now=True, max_length=30, verbose_name='Date/Time Added')),
                ('Comment', models.CharField(blank=True, max_length=300, verbose_name='username')),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=17, max_length=30, verbose_name='initial balance')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=17, max_length=30, verbose_name='debit')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=17, max_length=30, verbose_name='credit')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=17, max_length=30, verbose_name='balance')),
                ('order', models.IntegerField(blank=True, verbose_name='Order')),
                ('statement', models.CharField(blank=True, choices=[('BS', 'Balance sheet'), ('IS', 'Income statement'), ('CFS', 'Cash flow statement')], max_length=30, verbose_name='Financial Statement')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'security_questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('address', models.CharField(blank=True, max_length=254, verbose_name='address')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DateofBirth')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('security_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stonks.securityquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_answers',
            },
        ),
    ]
