# Generated by Django 2.2 on 2022-02-22 01:28
from django.db import migrations

def add_operations_group(apps, schema_editor):
    User = apps.get_model('Stonks', 'User')
    Group = apps.get_model('auth', 'Group')
    # Permission = apps.get_model('auth', 'Permission')

    Administrator = Group(name='Administrator')
    Administrator.save()

    Manager = Group(name='Manager')
    Manager.save()

    Accountant = Group(name='Accountant')
    Accountant.save()

    for user in User.objects.all():
        if user.role == 'Administrator':
            Administrator.user_set.add(user)
        if user.role == 'Accountant':
            Accountant.user_set.add(user)
        if user.role == 'Manager':
            Manager.user_set.add(user)



class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_operations_group),
    ]
