# Generated by Django 2.2 on 2022-02-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0003_auto_20220212_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
