# Generated by Django 2.2 on 2022-02-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_name', models.CharField(max_length=30, unique=True, verbose_name='Account Name')),
                ('account_number', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='Account Number')),
                ('account_description', models.CharField(blank=True, max_length=300, verbose_name='Account Description')),
                ('account_category', models.CharField(choices=[('A', 'Assets'), ('L', 'Liabilities'), ('EQ', 'Equity Accounts'), ('R', 'Revenues'), ('EX', 'Expenses'), ('O', 'Other')], max_length=30, verbose_name='Account Category')),
                ('account_subcategory', models.CharField(blank=True, max_length=30, verbose_name='Account Subcategory')),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Initial balance')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Credit')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Balance')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('statement', models.CharField(blank=True, choices=[('BS', 'Balance sheet'), ('IS', 'Income statement'), ('RE', 'Retained Earnings statement')], max_length=30, verbose_name='Financial Statement')),
                ('userid', models.IntegerField(blank=True, null=True, verbose_name='User id')),
                ('normal_side', models.CharField(blank=True, max_length=5, verbose_name='Normal Side')),
                ('Date_time_added', models.DateTimeField(auto_now=True, max_length=30, verbose_name='Date/Time Added')),
                ('Comment', models.CharField(blank=True, max_length=300, verbose_name='Comment')),
            ],
        ),
    ]
