# Generated by Django 4.0.3 on 2022-03-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
