# Generated by Django 4.0.3 on 2022-03-25 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0005_alter_securityquestion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='userid',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
