# Generated by Django 4.0.3 on 2022-03-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0006_remove_account_userid_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_added', models.DateField(auto_now=True, max_length=30, verbose_name='Date/Time Added')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description of Entry')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Amount')),
                ('Status', models.BooleanField(verbose_name='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stonks.account')),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Transaction',
            fields=[
                ('jt_id', models.AutoField(primary_key=True, serialize=False)),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stonks.journal')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stonks.transaction')),
            ],
        ),
    ]
