# Generated by Django 4.0.3 on 2022-03-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0007_journal_transaction_journal_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Status',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=30, null=True, verbose_name='Journal Status'),
        ),
    ]
