# Generated by Django 4.0.3 on 2022-04-09 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0007_journal_transaction_journal_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(blank=True, verbose_name='Date/Time')),
                ('date_updated', models.DateTimeField(blank=True, verbose_name='Date/Time')),
                ('file_name', models.CharField(max_length=500, verbose_name='File Name')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stonks.journal', verbose_name='Journal Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Stonks.journal'),
        ),
        migrations.DeleteModel(
            name='Journal_Transaction',
        ),
    ]
