# Generated by Django 4.0.3 on 2022-04-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0008_file_transaction_journal_delete_journal_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='journal',
        ),
        migrations.AddField(
            model_name='journal',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Stonks.file', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='journal',
            name='transaction',
            field=models.ManyToManyField(to='Stonks.transaction', verbose_name='Transaction'),
        ),
    ]
