# Generated by Django 4.0.3 on 2022-03-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stonks', '0008_rename_status_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Transaction Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.BooleanField(verbose_name='Transaction Type'),
        ),
    ]
