version: '3.1'

services:

  Stonks-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test1234,
      MYSQL_USER: admin,
      MYSQL_PASSWORD: password
    networks:
      - Stonks-net

  Stonks-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - Stonks-db
    networks:
      - Stonks-net

networks:
  Stonks-net: