version: '3.1'

services:

  stonks-db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
    ports:
      - 3307:3306
    networks:
      - Stonks-net

  stonks-adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - Stonks-db
    networks:
      - Stonks-net

networks:
  Stonks-net: