version: '3.1'

services:

  stonks-db:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${MY_USER}
      - MARIADB_PASSWORD=${MY_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      - 3307:3306
    networks:
      - Stonks-net

  stonks-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Stonks
    ports:
      - "9000:8000"
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${MY_USER}
      - POSTGRES_PASSWORD=${MY_PASSWORD}
    depends_on:
      - stonks-db
    networks:
      - Stonks-net

  stonks-adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
    depends_on:
      - stonks-db
    networks:
      - Stonks-net

networks:
  Stonks-net: